name: "build-dcevm manually"
on:
  workflow_dispatch:
    inputs:
      dcevm_branch:
        description: 'dcevm branch'
        required: true
        default: 'dcevm8u282b08'
      dcevm_tag:
        description: 'dcevm tag'
        required: true
        default: 'dcevm8u282b08'

jobs:
  dcevm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        javaToBuild: [jdk8u]
    steps:
    - uses: actions/checkout@v1
    - uses: TravaOpenJDK/action-build-dcevm@v1
      id: buildJDK
      with:
        impl: dcevm
        javaToBuild: ${{ matrix.javaToBuild}}
        dcevm_branch: ${{ github.event.inputs.dcevm_branch }}
        dcevm_tag: ${{ github.event.inputs.dcevm_tag }}
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
    - uses: actions/upload-artifact@v2
      with:
        name: '${{ steps.buildJDK.outputs.JdkPackageFileName }}'
        path: ${{ github.workspace }}/temurin-build-dcevm/workspace/artifacts/${{ steps.buildJDK.outputs.JdkPackageFileName }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/temurin-build-dcevm/workspace/artifacts/${{ steps.buildJDK.outputs.JdkPackageFileName }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
